const  CartActionsTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    ClEAR_ITEM_FROM_CART:'ClEAR_ITEM_FROM_CART',
    REMOVE_ITEM:'REMOVE_ITEM',
    CHANGE_PHOTO:'CHANGE_PHOTO'
}
export default CartActionsTypes;